## <span style="color:blue">Problem Set 12</span>

### <font color="blue">Overview</font>  
These problems require recursive solutions.  No points will be give for solutions that are not recursive.

### <font color="blue">Problem 1</font>
Write a recursive function called _power_ that does exponentiation. The function accepts two arguments: _num_ and _exp_.  The function takes _num_ and raises to the power _exp_.  The solution does not require any python functions, and obviously should not use the python exponentiation operator.

In [ ]:
def power(num, exp):
    if exp == 0:
        return 1
    return num * power(num, exp - 1)

print("2 to the 8th power is", power(2,8))
print("2 to the 15th power is", power(2,15))


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
2 to the 8th power is 256<br />
2 to the 15th power is 32768</div>   

### <font color="blue">Problem 2</font>
Write a recursive function called _reverseString_ that reverses a string passed as an argument. Do not use any python function to reverse the string.  The string must be reversed by your code.  The only python function required is len().  

In [ ]:
def reverseString(s):
    if len(s) == 0:
        return ""
    return reverseString(s[1:]) + s[0]

string_to_reverse = "the quick brown fox jumps over the lazy dog"
print("The original string:", string_to_reverse)
print("The reversed string:", reverseString(string_to_reverse))
print()
string_to_reverse = "able was I ere I saw elba"
print("The original string:", string_to_reverse)
print("The reversed string:", reverseString(string_to_reverse))


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The original string: the quick brown fox jumps over the lazy dog<br />
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht<br />
<br />
The original string: able was I ere I saw elba<br />
The reversed string: able was I ere I saw elba</div>   

### <font color="blue">Problem 3</font>
Write a recursive function called _reverseList_ that reverses a list passed as an argument. Do not use any python function to reverse the list.  The list must be reversed by your code.  The only python function required is len().  

In [1]:
def reverseList(lst):
    if len(lst) == 0:
        return []
    return reverseList(lst[1:]) + [lst[0]]

list_to_reverse = [1,2,3,4,5,6,7,8,9,0]
print("The original list:", list_to_reverse)
print("The reversed list:", reverseList(list_to_reverse))


The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]</br>
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]</div>

### <font color="blue">Problem 4</font>
Write a recursive function called _totalDigits_ that, given a number _n_ returns the sum of the digits of _n_.

In [ ]:
def totalDigits(n):
    if n < 10:
        return n
    return n % 10 + totalDigits(n // 10)

for m in [111,222,333,1076458]:
    print("The total of the digits in", m, "is", totalDigits(m))


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
TThe total of the digits in 111 is 3<br/>
The total of the digits in 222 is 6<br/>
The total of the digits in 333 is 9<br/>
The total of the digits in 1076458 is 31</span>  

### <font color="blue">Problem 5</font>
Write a recursive function called _convertToDecimal_ that accepts a binary number (string type) and converts it to decimal. Assume a valid binary number is passed so there is not need for error checking.  Also since the binary number passed is a string, you will need to coerce each digit into an integer using the int() function.  This function must work for any binary number of any length, so do not hard code position values.  Position values must be calculated by the function.

The value of the positions for binary numbers are:

    2**n  2**(n-1) ... 2**3  2**2  2**1  2**0   where 2**0 is 1

Determining the decimal value of a binary number:
  1. For each digit, multiply the digit by the value of the position
  2. Repeat step one for all digits in the binary number
  3. Add all the results together
  


In [2]:
def convertToDecimal(binary):
    if len(binary) == 1:
        return int(binary)
    return int(binary[0]) * (2 ** (len(binary) - 1)) + convertToDecimal(binary[1:])

for bin in ['11111111','10101010','111','1010111010']:
    print("The binary number", bin, "is", convertToDecimal(bin), "in decimal")


The binary number 11111111 is 255 in decimal
The binary number 10101010 is 170 in decimal
The binary number 111 is 7 in decimal
The binary number 1010111010 is 698 in decimal


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The binary number 11111111 is 255 in decimal<br />
The binary number 10101010 is 170 in decimal<br />
The binary number 111 is 7 in decimal<br />
The binary number 1010111010 is 698 in decimal<div>