## <span style="color:blue">Problem Set 4</span>

### <font color='blue'>Note:</font>
1. The variables in the first cell are used in later problems.  Do not duplicate the code in later cells or attempt to write similar code.

2. Use the variable names defined in the instructions for each problem.  Failure to do so will result in a loss of points.

3. You need to use code to arrive at a solution. Hard coding a solution results in 0 points for the problem.

4. Use only syntax covered in the Units so far. Using any other syntax results in 0 points for the problem.

Some problems below require text and csv files.  Files used in these problems must be co-resident with your notebook, otherwise a "file not found" error is thrown.  This means that your notebook file (.ipynb) and the text or csv file are visible in your home page.

### <font color="blue">Run the cell below first</font>
Before starting the assignment, run the cell below.  By running this cell, the variables and functions in that cell are loaded into the address space of your notebook, which makes them available to use in your code.

In [19]:
umSchools = {
  "A. Alfred Taubman College of Architecture & Urban Planning": 1906,
  "College of Engineering": 1854,
  "College of Literature, Science, and the Arts": 1841,
  "Gerald R. Ford School of Public Policy": 1914,
  "Horace H. Rackham School of Graduate Studies": 1912,
  "Penny W. Stamps School of Art & Design": 1974,
  "School of Dentistry": 1875,
  "School of Education": 1921,
  "School of Information": 1996,
  "School of Kinesiology": 1984,
  "School of Law": 1859,
  "School of Medicine": 1850,
  "School of Music, Theatre & Dance": 1880,
  "School of Natural Resources & Environment": 1927,
  "School of Nursing": 1893,
  "School of Pharmacy": 1876,
  "School of Public Health": 1941,
  "School of Social Work": 1951,
  "Stephen M. Ross School of Business": 1924
}

janTemps = """2016,   6, 51
        2015,  -3, 41
        2014, -14, 43
        2013,  -3, 60
        2012,   2, 55
        2011,   1, 52
        2010,   3, 47
        2009, -10, 39
        2008,   3, 62
        2007,   5, 50
        2006,  18, 53
        2005,  -3, 56
        2004,  -6, 55
        2003,  -5, 47
        2002,  11, 55
        2001,   1, 43
        2000,  -2, 56"""

 ### <font color="blue">Problem 1</font>
The dictionary _courses_ is a hypothetical schedule for a semester.  The key is the course code and the value is the number of credits. Print the course code along with the number of credits as shown in expected out. Also, use an accumulation pattern to find the total number of credits taken this semester and assign it to the variable _credits_. Print the variable _credits_ as shown below.

Do the following:
1. Iterate over courses:
   1.  Print the course code and credits.
   2.  Accumulate the credits in the variable _credits_.
2. Print the total credits

In [20]:
courses = {'CPS141':4, 'ENG101':3, 'CIS100':3, 'CNT206':4, 'MTH160':4}
# Initialize credits to 0 to start accumulation
credits = 0
# Iterate over each course code and credit value in the dictionary
for course, credit in courses.items():
    print(course, credit)
    # Add current course's credits to the running total
    credits += credit
    # Print the total after the loop finishes
print("Total credits this semester", credits)


CPS141 4
ENG101 3
CIS100 3
CNT206 4
MTH160 4
Total credits this semester 18


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />  
CPS141 4<br/>
ENG101 3<br/>
CIS100 3<br/>
CNT206 4<br/>
MTH160 4<br/>
Total credits this semester 18</div>

### <font color="blue">Problem 2</font>
The dictionary _umSchools_ maps the names of schools at Michigan to the year they were founded. Write code that creates a dictionary called _oldSchools_ that has the key/value pairs from _umSchools_ that correspond to the schools listed in the list _schools_.

Do the following:
1. Iterate over schools:
   1. Create a new dictionary using the current school as the key and the corresponding value from umSchools
2. Print _oldSchools_

In [21]:
schools = [ "College of Engineering","School of Nursing","School of Dentistry"]
# Initialize empty dictionary to store results
oldSchools = {}
# Iterate over the schools list
for school in schools:
     # Use each school name as a key and look up its founding year in umSchools
 oldSchools[school] = umSchools[school]
print(oldSchools)


{'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875}


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
{'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875}</div>

### <font color="blue">Problem 3</font>
Using the _umSchools_ dictionary defined in the first cell, write code to add the name of every school that was founded in the 20th century (after 1900) into a list _newerSchools_. Print the list *newerSchools* as shown below.

In [22]:
# Initialize an empty list to store schools founded in the 20th century
newerSchools = []
# Iterate over the umSchools dictionary to get each school name and founding year
for school, year in umSchools.items():
        # Check if the school was founded after 1900 (20th century)
    if year > 1900:
         # Add the school name to the newerSchools list
        newerSchools.append(school)
          # Print the school name with the required message
        print(f"{school} was founded in the 20th century.")


A. Alfred Taubman College of Architecture & Urban Planning was founded in the 20th century.
Gerald R. Ford School of Public Policy was founded in the 20th century.
Horace H. Rackham School of Graduate Studies was founded in the 20th century.
Penny W. Stamps School of Art & Design was founded in the 20th century.
School of Education was founded in the 20th century.
School of Information was founded in the 20th century.
School of Kinesiology was founded in the 20th century.
School of Natural Resources & Environment was founded in the 20th century.
School of Public Health was founded in the 20th century.
School of Social Work was founded in the 20th century.
Stephen M. Ross School of Business was founded in the 20th century.


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971">
There are a total of 11 schools that meet this criterion.  The output list must show all 11 schools<br/>
    <strong>Expected Output:</strong><br />
A. Alfred Taubman College of Architecture & Urban Planning was founded in the 20th century.<br />
Gerald R. Ford School of Public Policy was founded in the 20th century.<br />
Horace H. Rackham School of Graduate Studies was founded in the 20th century</div>

### <font color="blue">Problem 4</font>
Given the string _paragraph_ below, write code to determine the most common word in the string and assign it to the variable _commonWord_, assign the frequency to _maxWordCount_.  The is a case insensitive frequency which means that case must be disregarded.

There are two parts:
1. The first part requires a loop that builds a dictionary of words and their frequency.
2. The second part requires a max accumulation pattern to find the word with the largest count.

A) Do the following to build the frequency dictionary:
1. Split the paragraph into words and store in a variable.
2. Initialize an empty dictionary
3. Iterate over the variable:
   1. You need to remove punctuation from the word.  
      If the last character in the word is a ".", ",", or a ";":
         1. Remove the last character in the word
   2. Convert the word to lowercase.
   3. If the word is in the dictionary:
         1. Increment the value associated with the word.  
   4. Otherwise:
         1. Initialize a new key using the word and assign 1 to the value

B) Determine the word with the largest frequency:
1. Iterate over the keys dictionary created in part A.
   1. if the value associated with current key is greater than _maxWordCount_:
      1. Store the current key in _commonWord_.
      2. Store the value of the current key in _maxWordCount_.

C) Print
1. Print _commonWord_ and _maxWordCount_ as shown below. 

Punctuation in the sentence must be removed as your code processes the word. You will also need to convert the word to lowercase.  You may use the _split_, the _in_ operator, and the _lower_ function.

In [23]:
paragraph = """
He was getting  old and paunchy and his hair was falling fast,
And he sat around the Legion, telling stories of the past.
Of a war that he had fought in and the deeds that he had done,
In his exploits with his buddies; they were heroes, every one.
"""
# Part A: Build a frequency dictionary
words = paragraph.split() # Split paragraph into individual words
wordFreq = {}   # Initialize empty frequency dictionary
counts = {}
for word in words:
     # Remove trailing punctuation if the last character is . , or ;
    if word[-1] in ".,;":
        word = word[:-1]
         # Convert to lowercase for case-insensitive counting
    word = word.lower()
        # If word already in dictionary, increment its count
    if word in counts:
        counts[word] += 1
    else:
          # Otherwise add it with a count of 1
        counts[word] = 1
# Part B: Find the word with the highest frequency using max accumulation
maxWordCount = 0
commonWord = ""
for word in counts:
    if counts[word] > maxWordCount:
        maxWordCount = counts[word]
        commonWord = word
# Part C: Print the result
print(f"{commonWord} is the most common word with {maxWordCount} occurences")


he is the most common word with 4 occurences


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
he is the most common word with 4 occurences</div>

### <font color="blue">Problem 5</font>
Given the string _poem_ below, write code to determine the most common letter in the string and assign it to the variable _mostCommon_.  Also, assign the frequency of the most common letter to the variable _maxLetterCount_.  This is a case insensitive frequency which means lowercase and uppercase letters represent a single letter.

This problem is almost identical to problem 4 with the exception that you iterate over a string.  You should be able to make minor modifications to the code from problem 4 to achieve a solution.  Note, you need to skip spaces and punctuation.

Print _mostCommon_ and _maxLetterCount_ as shown below.

In [24]:
# A poem by Robert Frost
poem = """
Whose woods these are I think I know.
His house is in the village though;
He will not see me stopping here
To watch his woods fill up with snow.
My little horse must think it queer
To stop without a farmhouse near
Between the woods and frozen lake
The darkest evening of the year.
He gives his harness bells a shake
To ask if there is some mistake.
The only other sound’s the sweep
Of easy wind and downy flake.
The woods are lovely, dark and deep,
But I have promises to keep,
And miles to go before I sleep,
And miles to go before I sleep.
"""
#Build a letter frequency dictionar
letterCounts = {}
for char in poem:
    # Skip spaces and punctuation — only count letters
    char = char.lower()
    if char.isalpha():
         # Convert to lowercase for case-insensitive counting
        if char in letterCounts:
            letterCounts[char] += 1
        else:
            letterCounts[char] = 1
# Max accumulation to find the most common letter
# Initialize max accumulation variables
mostCommon = ""
maxLetterCount = 0
# Iterate over letterFreq to find the most common letter
for letter in letterCounts:
     if letterCounts[letter] > maxLetterCount:
        mostCommon = letter
        maxLetterCount = letterCounts[letter]

print(mostCommon, "is the most common letter with", maxLetterCount, "occurances")

print(mostCommon, "is the most common letter with", maxLetterCount, "occurances")

e is the most common letter with 66 occurances
e is the most common letter with 66 occurances


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
e is the most common letter with 66 occurances</div>

### <font color="blue">Problem 6</font>
Write code that creates the dictionary _vowelFrequency_ where the keys are the five vowels and the values represent their frequency in the string _sentence_. Using the _vowelFrequency_ dictionary and a max accumulation pattern determine the most common vowel and assign the result to the variable _commonVowel_.  Print the variable _commonVowel_ and the _vowelFrequency_ dictionary as shown below. 

The problem is similar to the previous problem.  The exception is that you need to select only vowels in the string sentence.

In [25]:
sentence = "singing in the rain and playing in the rain are two entirely different situations but both can be good fun"
vowels = ['a','e','i','o','u']
# Initialize the vowelFrequency dictionary with all 5 vowels set to 0
vowelFrequency = {}
for vowel in vowels:
    vowelFrequency[vowel] = 0
# Iterate over every character in the sentence
for char in sentence:
        # Only count it if it's a vowel
    char = char.lower()
    if char in vowelFrequency:
        vowelFrequency[char] += 1
# Max accumulation to find the most common vowel
maxVowelCount = 0
commonVowel = ""
for vowel in vowelFrequency:
    if vowelFrequency[vowel] > maxVowelCount:
        maxVowelCount = vowelFrequency[vowel]
        commonVowel = vowel

print(vowelFrequency)
print(f"The most common vowel is {commonVowel}")


{'a': 7, 'e': 8, 'i': 11, 'o': 5, 'u': 3}
The most common vowel is i


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br /> 
{'i': 11, 'e': 8, 'a': 7, 'o': 5, 'u': 3}<br />
The most common vowel is i</div>

### <font color="blue">Problem 7</font>
The string _janTemps_ contains January temperature information for Ann Arbor for the years 2015 through 2000. This string is formatted so that it consists of multiple lines.  Each line is composed of three “columns” separated by commas as shown below. 
1. Year.
2. Lowest temperature.
3. Highest temperature.

Write code that creates two dictionaries: _janLows_, which maps the year to the lowest temperature, and _janHighs_, which maps the year to the highest temperature. The key for each dictionary is the year, converted to an integer, and the value is the temperature, converted to an integer. 

Each line in the string is terminated by a new-line character.  You must use .split('\n') to split the lines of _janTemps_ into a list. This results in a list of strings where each string holds the three columns.  As you iterate over that list, split a given line using a "," into a list containing the three column values. Use int() to cast the year, low temperature, and high temperature to integers.

Print the variables _janLows_ and _janHighs_.

In [26]:
# Split the multi-line string into a list of lines
lines = janTemps.split('\n')

# Initialize empty dictionaries for lows and highs
janLows = {}
janHighs = {}
# Iterate over each line
for line in lines:
    parts = line.split(',')
    year = int(parts[0].strip())
    low = int(parts[1].strip())
    high = int(parts[2].strip())
       # Store in the appropriate dictionary
    janLows[year] = low
    janHighs[year] = high

print("January low temperatures:")
print(janLows)
print("\nJanuary high temperatures:")
print(janHighs)


January low temperatures:
{2016: 6, 2015: -3, 2014: -14, 2013: -3, 2012: 2, 2011: 1, 2010: 3, 2009: -10, 2008: 3, 2007: 5, 2006: 18, 2005: -3, 2004: -6, 2003: -5, 2002: 11, 2001: 1, 2000: -2}

January high temperatures:
{2016: 51, 2015: 41, 2014: 43, 2013: 60, 2012: 55, 2011: 52, 2010: 47, 2009: 39, 2008: 62, 2007: 50, 2006: 53, 2005: 56, 2004: 55, 2003: 47, 2002: 55, 2001: 43, 2000: 56}


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
January low temperatures:<br />
{2016: 6, 2015: -3, 2014: -14, 2013: -3, 2012: 2, 2011: 1, 2010: 3, 2009: -10, 2008: 3, 2007: 5, 2006: 18, 2005: -3, 2004: -6, 2003: -5, 2002: 11, 2001: 1, 2000: -2}<br /><br />
January high temperatures:<br />
{2016: 51, 2015: 41, 2014: 43, 2013: 60, 2012: 55, 2011: 52, 2010: 47, 2009: 39, 2008: 62, 2007: 50, 2006: 53, 2005: 56, 2004: 55, 2003: 47, 2002: 55, 2001: 43, 2000: 56}</div>

### <font color="blue">Problem 8</font>
Again using the string _janTemps_, write code that will determine which year had the largest difference between the lowest and highest temperature. Store the year, as an integer, in the variable  _maxTempDiffYear_ and temperature difference in the variable _maxTempDiff_.  

You need use much of the code from the above problem to parse each line in janTemps into the three values: year, lowest temperature, and the highest temperature.  Write additional code that uses a max accumulation pattern to calculate the largest temperature difference and the year when that difference occured.  Do not use the max function.

Print _maxTempDiffYear_  and _maxTempDiff_ as shown below.

In [27]:
# Initialize max accumulation variables
maxTempDiff = 0
maxTempDiffYear = 0

# Re-parse janTemps line by line
for line in janTemps.split('\n'):
    # Split each line by comma to get year, low, high
    parts = line.split(',')
    year = int(parts[0].strip())
    low  = int(parts[1].strip())
    high = int(parts[2].strip())

    # Calculate the difference between high and low
    diff = high - low

    # Update if this is the largest difference seen so far
    if diff > maxTempDiff:
        maxTempDiff = diff
        maxTempDiffYear = year

print("In January of", maxTempDiffYear, "the difference between high and low temperatures was", maxTempDiff)


In January of 2013 the difference between high and low temperatures was 63


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
In January of 2013 the difference between high and low temperatures was 63</div>

### <font color="blue">Problem 9</font>
The text file _Unit04_wnvhumancases1.txt_ contains data on West Nile virus infections in the United States from 2006 through 2018. Each record (line) in the file has four columns(values) separated by a comma. Each column is described below.

    Column 1:  Year (reported)
    Column 2:  Week (week reported)
    Column 3:  County
    Column 4:  Cases (number of cases reported)

Process the file and use an accumulation pattern to provide a count of the number of records(lines) and total of the number of cases.  The count of lines in the file must be stored in _numRecs_ and the total number of cases in the variable _numCases_.  Make sure you close the file after processing the data.

Hint:  Since this is a text file each line is a string. You will need to split the line into a list of values and convert those values to integer .

Print the variables _numRecs_  and _numCases_ as shown below.

In [28]:
# Initialize accumulators
numRecs  = 0
numCases = 0

# Open and read the csv text file
f = open("Data/Unit04_wnvhumancases.csv", "r")

# Skip the header row
next(f)

for line in f:
    # Split each line by comma to get the 4 columns
    parts = line.split(',')
    # Count each record
    numRecs += 1
    # Add the cases column (4th column) to total
    numCases += int(parts[3])

# Always close the file after reading
f.close()

print("Total number of records:", numRecs)
print("Total number of cases:", numCases)

Total number of records: 1789
Total number of cases: 4993


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
Total number of records: 1789<br />
Total number of cases: 4993</div>

### <font color="blue">Problem 10</font>
The csv file _Unit04_wnvhumancases.csv_ is identical to the text file used in the previous proble, with the exception that it contains a header line and all fields are delimited by double-quotes.  The column names are shown below.

    Column 1:  Year (reported)
    Column 2:  Week (week reported)
    Column 3:  County
    Column 4:  Cases (number of cases reported)

You must use csv module to process the file and use an accumulation pattern to provide a count of the number of records in the file in the variable _numRows_ and the total number of incidents, i.e., a total of Positive Cases, in the variable _numIncidents_.  

You also need to identify the county with the highest number of incidents in the variable _maxCounty_, the year that the highest number of incidents occurred  in the variable _maxCountyYear_, and the number of incidents in that county in _maxCountyIncidents_.

Do the same as the above but for the minimum,  Store the results in _minCounty_, _minCountyYear_, and _minCountyIncidents_. 

Print the information as shown below.

In [29]:
import csv

# Initialize all accumulators
numRows = 0
numIncidents = 0
maxCountyIncidents = 0
maxCounty = ""
maxCountyYear = 0
minCountyIncidents = float('inf')
minCounty = ""
minCountyYear = 0

# Open and read the CSV file
with open("Data/Unit04_wnvhumancases.csv", "r") as f:
    reader = csv.reader(f)
    # Skip the header row
    next(reader)

    for row in reader:
        year   = int(row[0])
        county = row[2]
        cases  = int(row[3])

        # Count records and accumulate total incidents
        numRows += 1
        numIncidents += cases

        # Max accumulation for county with most cases
        if cases > maxCountyIncidents:
            maxCountyIncidents = cases
            maxCounty = county
            maxCountyYear = year

        # Min accumulation for county with fewest cases
        if cases < minCountyIncidents:
            minCountyIncidents = cases
            minCounty = county
            minCountyYear = year

print("Total cases:             ", numRows)
print("Total incidents:         ", numIncidents)
print("The county with the largest number of cases is", maxCounty + ", with", maxCountyIncidents, "incidents reported in the year", maxCountyYear)
print("The county with the smallest number of cases is", minCounty + ", with", minCountyIncidents, "incidents reported in the year", minCountyYear)



Total cases:              1789
Total incidents:          4993
The county with the largest number of cases is Los Angeles, with 40 incidents reported in the year 2017
The county with the smallest number of cases is Alameda, with 1 incidents reported in the year 2006


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
Total cases:              1789<br />
Total incidents:          4993<br />
The county with the largest number of cases is Los Angeles, with 40 incidents reported in the year 2017<br />
The county with the smallest number of cases is Alameda, with 1 incidents reported in the year 2006</div>

### <font color="blue">Run the cells below to test your code</font>

In [30]:
import unittest

class PS04_01 (unittest.TestCase):
    def test_problem01(self):
        self.assertEqual(credits, 18)
class PS04_02 (unittest.TestCase):
    def test_problem02(self):
        self.assertEqual(oldSchools, {'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875})
class PS04_03 (unittest.TestCase):
    def test_problem03(self):
        self.assertTrue(type(newerSchools) is list) 
        self.assertEqual(len(newerSchools), 11)
class PS04_04 (unittest.TestCase):
    def test_problem04(self):
        self.assertEqual(commonWord, 'he')
        self.assertEqual(maxWordCount, 4)
class PS04_05 (unittest.TestCase):
    def test_problem05(self):
        self.assertEqual(mostCommon, 'e')
        self.assertEqual(maxLetterCount, 66)        
class PS04_06 (unittest.TestCase):
    def test_problem06(self):
        self.assertEqual(commonVowel, 'i')
        self.assertEqual(vowelFrequency['i'], 11)
        self.assertEqual(vowelFrequency,{'i': 11, 'e': 8, 'a': 7, 'o': 5, 'u': 3})
class PS04_07 (unittest.TestCase):
    def test_problem07(self):
        self.assertTrue(type(janLows) is dict) 
        self.assertTrue(type(janHighs) is dict) 
        self.assertEqual(janLows[2016], 6)
        self.assertEqual(janHighs[2016], 51)
class PS04_08 (unittest.TestCase):
    def test_problem08(self):
        self.assertEqual(maxTempDiffYear, 2013)
        self.assertEqual(maxTempDiff, 63)
class PS04_09 (unittest.TestCase):
    def test_problem09(self):
        self.assertEqual(numRecs, 1789)
        self.assertEqual(numCases, 4993)
class PS04_10 (unittest.TestCase):
    def test_problem10(self):
        self.assertEqual(numRows, 1789)
        self.assertEqual(numIncidents, 4993)
        self.assertEqual(maxCounty, 'Los Angeles')
        self.assertEqual(maxCountyIncidents, 40)
        self.assertEqual(maxCountyYear, 2017)     

In [32]:
unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

test_problem01 (__main__.PS04_01.test_problem01) ... ok
test_problem02 (__main__.PS04_02.test_problem02) ... ok
test_problem03 (__main__.PS04_03.test_problem03) ... ok
test_problem04 (__main__.PS04_04.test_problem04) ... ok
test_problem05 (__main__.PS04_05.test_problem05) ... ok
test_problem06 (__main__.PS04_06.test_problem06) ... ok
test_problem07 (__main__.PS04_07.test_problem07) ... ok
test_problem08 (__main__.PS04_08.test_problem08) ... ok
test_problem09 (__main__.PS04_09.test_problem09) ... ok
test_problem10 (__main__.PS04_10.test_problem10) ... ok

----------------------------------------------------------------------
Ran 10 tests in 0.014s

OK
