## <span style="color:blue">Problem Set 8</span>

### <font color='blue'>Note:</font>
1. The variables in the first cell are used in later problems.  Do not duplicate the code in later cells.

2. Use the variable names defined in the instructions for each problem.  Failure to do so will result in a loss of points.

3. You need to use code to arrive at a solution. Hard coding a solution results in 0 points for the problem.

4. Use only syntax covered in the Units so far. Using any other syntax results in 0 points for the problem.

### <font color="blue">Run the cell below first</font>
Before starting the assignment, run the cell below.  By running this cell, the variables and/or functions in that cell are loaded into the address space of your notebook, which makes them available to use in your code.

In [3]:
import csv
import json
import sys

# I add the assignments folder to the path so Python can find the vincenty module
sys.path.insert(0, '/Users/dylankur/PycharmProjects/dylankurcps141/assignments')
from Unit08_vincenty import latLngDistanceMeters

# I open the buildings JSON file for reading
fh = open('/Users/dylankur/PycharmProjects/dylankurcps141/assignments/Unit08_umich_buildings.json','r')
umich_buildins_str = fh.read()
umich_buildings = json.loads(umich_buildins_str)
fh.close()

# I open the baby names CSV file and load it into a list
baby_file = open('/Users/dylankur/PycharmProjects/dylankurcps141/assignments/Unit08_us-common-baby-names.csv','r')
baby_reader = csv.DictReader(baby_file)
baby_names = list(baby_reader)

The variable *umich_buildings* is list where each element is a dictionary.  The keys in the dictionary contained in each list element are: 

<table>
  <tr>
    <th style="text-align: center">Key</th>
    <th style="text-align: center">Description</th> 
  </tr>
  <tr>
    <td style="text-align: center">address</td>
    <td  style="text-align: left">The address of the building</td> 
  </tr>
  <tr>
    <td style="text-align: center">id</td>
    <td  style="text-align: left">The building id, e.g.,asb is Administrative Services Building </td> 
  </tr>
  <tr>
    <td style="text-align: center">lat</td>
    <td  style="text-align: left">The geographic latitude,i.e., north-south position of a point on the Earth's surface</td> 
  </tr>
  <tr>
    <td style="text-align: center">lng</td>
    <td  style="text-align: left">The geographic longitude,i.e.,the angular distance of a place east or west of the meridian at Greenwich, England</td> 
  </tr>
  <tr>
    <td style="text-align: center">name</td>
    <td  style="text-align: left">The building name</td> 
  </tr>
</table>

Below is a typical element in the list:  
{  
&nbsp;&nbsp;&nbsp;&nbsp;"address": "1201 South Main Street Ann Arbor, MI 48104-3722",  
&nbsp;&nbsp;&nbsp;&nbsp;"id": "stadm",  
&nbsp;&nbsp;&nbsp;&nbsp;"lat": 42.265071,  
&nbsp;&nbsp;&nbsp;&nbsp;"lng": -83.748662,  
&nbsp;&nbsp;&nbsp;&nbsp;"name": "Michigan Stadium"  
}  

### <font color="blue">Problem 1<font>
Write a function named _buildingLatLong_ that is passed a building id, searches _umich_buildings_ for that id, and, if found, and returns a tuple whose elements are (name,latitude, longitude) of the corresponding building. If the building id is not found in _umich_buildings_, the function must return None. 

Write code that iterates over the list _bldgs_, containing building ids, calls _buildingLatLong_, and prints the information as shown. 

In [4]:
bldgs = ['ccrb','aep','taubl','unknown','nq','stadm']

def buildingLatLong(building_id):
    # I search through the umich_buildings list to find the matching building id
    for building in umich_buildings:
        if building['id'] == building_id:
            # I return a tuple of name, latitude, and longitude when I find a match
            return (building['name'], building['lat'], building['lng'])
    # I return None if the building id was not found in the list
    return None

# I iterate over the bldgs list and print the result of each lookup
for b in bldgs:
    print(buildingLatLong(b))

('Central Campus Recreation Building', 42.278866, -83.732666)
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)
None
('North Quadrangle', 42.280477, -83.740131)
('Michigan Stadium', 42.265071, -83.748662)


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
('Central Campus Recreation Building', 42.278866, -83.732666)<br/>
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)<br/>
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)<br/>
None<br/>
('North Quadrangle', 42.280477, -83.740131)<br/>
('Michigan Stadium', 42.265071, -83.748662</div>

### <font color="blue">Problem 2</font>
"Vincenty's formulas are two related iterative methods used to calculate the distance between two points on the surface of a spheroid, developed by Thaddeus Vincenty (1975a)"

The file _Unit08_vincenty.py_, which was imported in the first cell, contains the function _latLngDistanceMeter_ that calculates the _vincenty_ distance" in meters between two points on the Earth using the latitude and longitude of each points. The function accepts two tuples each containing the latitude and longitude of a point and calculates the _vincenty_ distance between those points. Below is an example of how this function is called:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;latLngDistanceMeters((42.3584, -71.0912), (42.278, -83.7382))

Write a function named _buildingDistance_ that is passed two building IDs and determines the vincenty distance between both buildings. The function uses the function _buildingLatLong_, developed in the previous problem, to find the longitude and latidude of each building and calls _latLngDistanceMeters_ to determine and return the _vincenty_ distance.  If one or both building ids are invalid, i.e., buildingLatLong returns None, return _False_ as the distance.

In the main part of your code, iterate over the list _bldgs_ below and call _buildingDistance_ for each tuple in the list. Print the output below.

In [6]:
bldgs = [('ccrb','aep'),('taubl','nq'),('bid1','bid2'),('ccrb','bid1'),('bid2','bid2nq')]

def buildingDistance(id1, id2):
    # I use my buildingLatLong function to get the coordinates of each building
    b1 = buildingLatLong(id1)
    b2 = buildingLatLong(id2)
    # I return False if either building id is invalid (not found)
    if b1 is None or b2 is None:
        return False
    # I pass the lat/lng of both buildings to latLngDistanceMeters and return the result
    return latLngDistanceMeters((b1[1], b1[2]), (b2[1], b2[2]))

# I iterate over the list of building pairs and print the vincenty distance for each
for pair in bldgs:
    dist = buildingDistance(pair[0], pair[1])
    print(f"The vincenty distance between building {pair[0]} and {pair[1]} is {dist}")

The vincenty distance between building ccrb and aep is 2414.804664314602
The vincenty distance between building taubl and nq is 575.5430991021018
The vincenty distance between building bid1 and bid2 is False
The vincenty distance between building ccrb and bid1 is False
The vincenty distance between building bid2 and bid2nq is False


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The vincenty distance between building ccrb and aep is 2414.804664314602<br />
The vincenty distance between building taubl and nq is 575.5430991014669<br />
The vincenty distance between building bid1 and bid2 is False<br />
The vincenty distance between building ccrb and bid1 is False<br />
The vincenty distance between building bid2 and bid2nq is False</div>

### <font color="blue">Problem 3:</font> 
Write code that iterates over _umich_buildings_ and outputs a _.csv_ file called _north_quad_distance.csv_. 

The csv file has two columns: 

1. The building name.
2. The vincenty distance of that building from North Quad(nq).

Since this is a csv file, the first row in the file is a header that identifies the two columns.  Column 1 of the first row has the value "Name" and column 2 has the value "Distance from NQ". There should be one subsequent row for each building (including North Quad, which should have a zero distance).  You should use the string .format() function to format each row in the csv file.

Check your work by opening the .csv file in a text editor or importing it into a spreadsheet program like Excel or Google Sheets.

You file should appear similar to that below:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name,Distance from NQ  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1000 Victors Way,4674.366005  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1032 Greene Building,1498.650608  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;523 South Division Building,639.5818755  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Administrative Services Building,1410.470849  

In [7]:
# I look up the coordinates of North Quad to use as my reference point
nq = buildingLatLong('nq')

# I open the output csv file for writing
f = open('north_quad_distance.csv', 'w')

# I write the header row with column names
f.write("Name,Distance from NQ\n")

# I iterate over every building and calculate its distance from North Quad
for building in umich_buildings:
    dist = latLngDistanceMeters((nq[1], nq[2]), (building['lat'], building['lng']))
    # I write each building name and distance as a formatted csv row
    f.write("{},{:.6f}\n".format(building['name'], dist))

f.close()  # I close the file when I am done writing
print("File written successfully.")

File written successfully.


### <font color="blue">Problem 4</font>
This problem uses the list _baby_names_ loaded from Unit08_us-common-baby-names.csv (see first cell). Each element in the baby_names list is a dictionary.  The keys in the dictionary are 'year', 'name','percent',and 'sex'.  A sample row appears below.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{'year': '1880', 'name': 'John', 'percent': '0.081541', 'sex': 'boy'}
             
The _percent_ key holds a percentage value, represented as a fraction, which represents the number of babies born that year who were given the name found in the value of the _name_ key.   

Write the function _popularInYear_ that accepts the  parameter _year_ and returns the most popular name for that year and the associated percent. The most popular name is the one with the largest percentage.  This problem is essentially finding the maximum percentage in the _baby_names_ list that matches the _year_ parameter.  

Write code the iterates over the _years_ list and prints the most popular name for each year as shown below.  Note, that you need to multiply the _percent_ value by 100 to print that value as a percentage.

In [8]:
years = ['1900','1925','1950','1975','2000','2004','2008']

def popularInYear(year):
    # I initialize best to None and update it as I find higher percentages
    best = None
    for entry in baby_names:
        # I only consider entries that match the year I am looking for
        if entry['year'] == year:
            if best is None or float(entry['percent']) > float(best['percent']):
                best = entry  # I update best when I find a higher percentage
    return best

# I iterate over each year and print the most popular name and its percentage
for year in years:
    result = popularInYear(year)
    print(f"Most popular name in {year} is {result['name']} with {float(result['percent'])*100:.2f} percent")

Most popular name in 1900 is John with 6.06 percent
Most popular name in 1925 is Mary with 5.59 percent
Most popular name in 1950 is James with 4.73 percent
Most popular name in 1975 is Michael with 4.22 percent
Most popular name in 2000 is Jacob with 1.65 percent
Most popular name in 2004 is Jacob with 1.32 percent
Most popular name in 2008 is Jacob with 1.04 percent


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
Most popular name in 1900 is John with 6.06 percent<br/>
Most popular name in 1925 is Mary with 5.59 percent<br/>
Most popular name in 1950 is James with 4.73 percent<br/>
Most popular name in 1975 is Michael with 4.22 percent<br/>
Most popular name in 2000 is Jacob with 1.65 percent<br/>
Most popular name in 2004 is Jacob with 1.32 percent<br/>
Most popular name in 2008 is Jacob with 1.04 percent</div>

### <font color="blue">Nested Data and Nested Iteration</font>
Many web services return information either in a json or xml format.  Below is sample json return by the Facebook API and is representative in structure of the json returned by most web services.  You will be working with nested data in future units.  This problem will serve as a warmup for those future problem sets.

First, just get familiar with the structure of the data. You may want to copy and paste it to a site like https://jsoneditoronline.org/ so you may inspect the data.

Run the cell below before proceeding to the problems.

In [9]:
fb_data = {
 "data": [
  {
    "id": "2253324325325123432madeup", 
    "from": {
      "id": "23243152523425madeup", 
      "name": "Jane Smith"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "This problem might use the accumulation pattern, like many problems do", 
    "type": "status", 
    "created_time": "2014-10-03T02:07:19+0000", 
    "updated_time": "2014-10-03T02:07:19+0000"
  }, 
 
  {
    "id": "2359739457974250975madeup", 
    "from": {
      "id": "4363684063madeup", 
      "name": "John Smythe"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "Here is a fun link about programming", 
    "type": "status", 
    "created_time": "2014-10-02T20:12:28+0000", 
    "updated_time": "2014-10-02T20:12:28+0000"
  }]
}

### <font color="blue">Problem 5</font>
Extract the contents of the first message into a variable called *first_message*.  Print *first_message*.

In [10]:
# I access the first item in the data list and extract its message value
first_message = fb_data['data'][0]['message']
print(first_message)

This problem might use the accumulation pattern, like many problems do


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
This problem might use the accumulation pattern, like many problems do</div>

### <font color="blue">Problem 6<font>
Extract the name of the author of the second post, into a variable called *second_name*.  Print *second_name*.

In [11]:
# I navigate into the second post's 'from' dictionary to get the author's name
second_name = fb_data['data'][1]['from']['name']
print(second_name)

John Smythe


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
John Smythe</div>

### <font color="blue">Problem 7</font>
Write code that generates a list of the names of all the authors of the messages in fb_data. Store it in a variable called _authors_.  Print the variable _authors_.

In [12]:
# I build a list of author names by iterating over every post in fb_data
authors = [post['from']['name'] for post in fb_data['data']]
print(authors)

['Jane Smith', 'John Smythe']


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
['Jane Smith', 'John Smythe']</div>

### <font color="blue">Run the cell below before completing the problems that follow.</font>

In [13]:
zipCodeData = [
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Alpena",
            "longitude": "-83.4602",
            "post code": "49707",
            "latitude": "45.079"
         }
      ],
      "country": "United States",
      "place name": "Alpena",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Hubbard Lake",
            "longitude": "-83.6059",
            "post code": "49747",
            "latitude": "44.8947"
         }
      ],
      "country": "United States",
      "place name": "Hubbard Lake",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Suttons Bay",
            "longitude": "-85.6423",
            "post code": "49682",
            "latitude": "44.9656"
         }
      ],
      "country": "United States",
      "place name": "Suttons Bay",
      "state": "Michigan",
      "state abbreviation": "MI"
   }
]

### <font color="blue">Problem 8</font>
Write code that iterates of the zipCodeData list and prints the nested _places_ list where the _place name_ (first-level place name) has a value of Hubbard Lake. 

In [14]:
# I iterate over zipCodeData and print the nested places list for Hubbard Lake
for entry in zipCodeData:
    if entry['place name'] == 'Hubbard Lake':
        print(entry['places'])

[{'place name': 'Hubbard Lake', 'longitude': '-83.6059', 'post code': '49747', 'latitude': '44.8947'}]


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
[{'place name': 'Hubbard Lake', 'longitude': '-83.6059', 'post code': '49747', 'latitude': '44.8947'}]</div>

### <font color="blue">Problem 9</font>
Write a function called _getZipData_ that accepts a _post code_ (zip code) as an argument and returns a tuple containing the associated _place name_, _longitude_, and _latitude_ for _zipCodeData_.  If the _post code_ passed to the function is not in the zipCodeData list, the returned tuple should have a value of None, 0, and 0 for the _place name_, _latitude_, and _longitude_ respectively.

Do the following in the function:
1. Initialize variables as necessary.
2. Iterate over _zipCodeData_: 
   1. Iterate over nexted _places_ list:
      1. If _post code_ in the current place is equal to the _post code_ passed:
         1. Store the _place name, _longitude_, and _latitude in the variables
3. Return the variables as a tuple

In [15]:
def getZipData(post_code):
    # I initialize my return variables to default values in case the zip is not found
    place_name = None
    longitude = 0
    latitude = 0
    # I iterate over each entry in zipCodeData and then over its nested places list
    for entry in zipCodeData:
        for place in entry['places']:
            # I check if the current place's post code matches what I was passed
            if place['post code'] == post_code:
                place_name = place['place name']
                longitude = place['longitude']
                latitude = place['latitude']
    # I return a tuple of place name, longitude, and latitude
    return (place_name, longitude, latitude)

# Do not change the code below
for zipcode in ['49682','49707','11111']:
     print(getZipData(zipcode))

('Suttons Bay', '-85.6423', '44.9656')
('Alpena', '-83.4602', '45.079')
(None, 0, 0)


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
('Suttons Bay', '-85.6423', '44.9656')<br />
('Alpena', '-83.4602', '45.079')<br />
(None, 0, 0)</div>

### <font color="blue">Problem 10</font>
Using the functions getZipData and latLngDistanceMeters write code that calculates the vincenty distance in kilometers between zip codes 49707 and 49747.  Print the output __exactly__ as shown below.  

The latLngDistanceMeters returns the distance in meters.  To convert to kilometers, divide the returned value by 1000.  

In [16]:
# I look up the zip data for both zip codes using my getZipData function
data1 = getZipData('49707')  # Alpena
data2 = getZipData('49747')  # Hubbard Lake

# I convert meters to kilometers by dividing by 1000
dist = latLngDistanceMeters((float(data1[2]), float(data1[1])), (float(data2[2]), float(data2[1]))) / 1000

# I print the result formatted to 2 decimal places with the city names
print(f"The vincenty distance between {data1[0]} and {data2[0]} is {dist:.2f}km")

The vincenty distance between Alpena and Hubbard Lake is 23.48km


<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The vincenty distance between Alpena and Hubbard Lake is 23.48km</div>