## <span style="color:blue">Problem Set 8</span>

<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem Set 8: Data File Organization

### These JSON and data files should really be stored in the repository&apos;s `assignments/Data` directory instead of kept in one flat assignment folder.

### A helpful pattern is to store the data directory path in one variable and each file name in its own variable. Then you can build full file paths from those pieces, which makes the code easier to update if the folder location changes later.

### For example, because this notebook is inside `assignments`, `data_dir` can point to `Data`. In the full repository, that folder is `assignments/Data`, while `buildings_file` stores only `Unit08_umich_buildings.json`. The code can then combine them when opening the file.
</div>

In [36]:
import os

# Store the folder path in one place
# This notebook is inside the assignments folder, so Data is the relative path from this notebook to the data folder.
data_dir = "Data"
output_dir = os.path.join(data_dir, "Output")

# Store each file name in its own variable
buildings_filename = "Unit08_umich_buildings.json"
baby_names_filename = "Unit08_us-common-baby-names.csv"
vincenty_filename = "Unit08_vincenty.py"
north_quad_output_filename = "north_quad_distance.csv"

# Build full paths by combining the folder path and file names
buildings_path = os.path.join(data_dir, buildings_filename)
baby_names_path = os.path.join(data_dir, baby_names_filename)
vincenty_path = os.path.join(data_dir, vincenty_filename)
north_quad_output_path = os.path.join(output_dir, north_quad_output_filename)

# Print the variables and paths to confirm they are set
print("Current working directory:", os.getcwd())
print()

print("Folder paths:")
print("data_dir:", data_dir)
print("output_dir:", output_dir)
print()

print("File name variables:")
print("buildings_filename:", buildings_filename)
print("baby_names_filename:", baby_names_filename)
print("vincenty_filename:", vincenty_filename)
print("north_quad_output_filename:", north_quad_output_filename)
print()

print("Full path variables:")
print("buildings_path:", buildings_path)
print("baby_names_path:", baby_names_path)
print("vincenty_path:", vincenty_path)
print("north_quad_output_path:", north_quad_output_path)

Current working directory: /Users/cv19-10260755/PycharmProjects/hif720/cps141_4_kur/assignments

Folder paths:
data_dir: Data
output_dir: Data/Output

File name variables:
buildings_filename: Unit08_umich_buildings.json
baby_names_filename: Unit08_us-common-baby-names.csv
vincenty_filename: Unit08_vincenty.py
north_quad_output_filename: north_quad_distance.csv

Full path variables:
buildings_path: Data/Unit08_umich_buildings.json
baby_names_path: Data/Unit08_us-common-baby-names.csv
vincenty_path: Data/Unit08_vincenty.py
north_quad_output_path: Data/Output/north_quad_distance.csv


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem Set 8: Path Formatting and File Names

### `os.path.join()` is a good way to build file paths because it automatically uses the correct path separator for the operating system. This keeps the path cleaner than manually typing slashes.

```python
import os

data_dir = "Data"
buildings_path = os.path.join(data_dir, "Unit08_umich_buildings.json")

print(buildings_path)
```

### On macOS or Linux, this outputs `Data/Unit08_umich_buildings.json`. On Windows, Python would format the path with backslashes instead.

### File names should also stay clean and consistent. A name like `Unit08_umich_buildings (1).json` usually means the file was downloaded more than once, and the computer added `(1)` to avoid overwriting the first copy. Data files should use a clear naming structure, such as `Unit08_umich_buildings.json`, without extra copy numbers or spaces.

### If you clean up a file name, you only need to update the variable once. For example, if `Unit08_umich_buildings (1).json` is renamed to `Unit08_umich_buildings.json`, then this one line should be updated:

```python
buildings_filename = "Unit08_umich_buildings.json"
```

### Because `buildings_path` is built from `buildings_filename`, the corrected file name is inherited anywhere else in the notebook that uses `buildings_path`.

### It is also helpful to print path variables after creating them. Printing values lets you confirm that the variables are set correctly and lets you see the result in the output area below the notebook cell.

```python
print("data_dir:", data_dir)
print("buildings_path:", buildings_path)
print("baby_names_path:", baby_names_path)
```

### This kind of quick check can catch path or filename mistakes before later cells try to open the files.
</div>

### <font color='blue'>Note:</font>
1. The variables in the first cell are used in later problems.  Do not duplicate the code in later cells.

2. Use the variable names defined in the instructions for each problem.  Failure to do so will result in a loss of points.

3. You need to use code to arrive at a solution. Hard coding a solution results in 0 points for the problem.

4. Use only syntax covered in the Units so far. Using any other syntax results in 0 points for the problem.

### <font color="blue">Run the cell below first</font>
Before starting the assignment, run the cell below.  By running this cell, the variables and/or functions in that cell are loaded into the address space of your notebook, which makes them available to use in your code.

In [37]:
import csv
import json
import sys

# Add the Data folder to the path so Python can find the vincenty module
sys.path.insert(0, data_dir)
from Unit08_vincenty import latLngDistanceMeters

# Open the buildings JSON file for reading
fh = open(buildings_path, "r")
umich_buildins_str = fh.read()
umich_buildings = json.loads(umich_buildins_str)
fh.close()

# Open the baby names CSV file and load it into a list
baby_file = open(baby_names_path, "r")
baby_reader = csv.DictReader(baby_file)
baby_names = list(baby_reader)
baby_file.close()

print("Setup complete.")
print("Loaded latLngDistanceMeters from", vincenty_path)
print("Loaded", len(umich_buildings), "building records from", buildings_path)
print("Loaded", len(baby_names), "baby name records from", baby_names_path)

Setup complete.
Loaded latLngDistanceMeters from Data/Unit08_vincenty.py
Loaded 161 building records from Data/Unit08_umich_buildings.json
Loaded 25800 baby name records from Data/Unit08_us-common-baby-names.csv


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem Set 8: Code Comment Style

### Comments should explain what the code is doing or why the code is needed. In code comments, avoid writing from the first-person point of view.

### For example, this comment is less professional because it says `I`:

```python
# I add the Data folder to the path so Python can find the vincenty module
```

### A clearer version describes the purpose of the line directly:

```python
# Add the Data folder to the path so Python can find the vincenty module
```

### If you use AI to help write or revise code, it can be helpful to give the AI a formatting guide. A repository-level `.skills` file or folder can describe how code, notebooks, markdown cells, and comments should be formatted so the style stays consistent across the notebook.
</div>

The variable *umich_buildings* is list where each element is a dictionary.  The keys in the dictionary contained in each list element are: 

<table>
  <tr>
    <th style="text-align: center">Key</th>
    <th style="text-align: center">Description</th> 
  </tr>
  <tr>
    <td style="text-align: center">address</td>
    <td  style="text-align: left">The address of the building</td> 
  </tr>
  <tr>
    <td style="text-align: center">id</td>
    <td  style="text-align: left">The building id, e.g.,asb is Administrative Services Building </td> 
  </tr>
  <tr>
    <td style="text-align: center">lat</td>
    <td  style="text-align: left">The geographic latitude,i.e., north-south position of a point on the Earth's surface</td> 
  </tr>
  <tr>
    <td style="text-align: center">lng</td>
    <td  style="text-align: left">The geographic longitude,i.e.,the angular distance of a place east or west of the meridian at Greenwich, England</td> 
  </tr>
  <tr>
    <td style="text-align: center">name</td>
    <td  style="text-align: left">The building name</td> 
  </tr>
</table>

Below is a typical element in the list:  
{  
&nbsp;&nbsp;&nbsp;&nbsp;"address": "1201 South Main Street Ann Arbor, MI 48104-3722",  
&nbsp;&nbsp;&nbsp;&nbsp;"id": "stadm",  
&nbsp;&nbsp;&nbsp;&nbsp;"lat": 42.265071,  
&nbsp;&nbsp;&nbsp;&nbsp;"lng": -83.748662,  
&nbsp;&nbsp;&nbsp;&nbsp;"name": "Michigan Stadium"  
}  

### <font color="blue">Problem 1<font>
Write a function named _buildingLatLong_ that is passed a building id, searches _umich_buildings_ for that id, and, if found, and returns a tuple whose elements are (name,latitude, longitude) of the corresponding building. If the building id is not found in _umich_buildings_, the function must return None. 

Write code that iterates over the list _bldgs_, containing building ids, calls _buildingLatLong_, and prints the information as shown. 

In [38]:
bldgs = ['ccrb','aep','taubl','unknown','nq','stadm']

def buildingLatLong(building_id):
    # Search through the umich_buildings list to find the matching building id
    for building in umich_buildings:
        if building['id'] == building_id:
            # Return a tuple of name, latitude, and longitude when a match is found
            return (building['name'], building['lat'], building['lng'])
    # Return None if the building id was not found in the list
    return None

# Iterate over the bldgs list and print the result of each lookup
for b in bldgs:
    print(buildingLatLong(b))

('Central Campus Recreation Building', 42.278866, -83.732666)
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)
None
('North Quadrangle', 42.280477, -83.740131)
('Michigan Stadium', 42.265071, -83.748662)


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 1: Alternative Test Inputs

### Another approach would be to write a small helper function that randomly selects five building IDs from `umich_buildings`. That randomly generated list could then be passed through the existing `buildingLatLong` function.

### This would make the test cases come from the actual data file instead of only using a manually written list. It is also a useful way to practice separating tasks: one function can choose sample building IDs, while `buildingLatLong` stays focused on looking up one building ID.

```python
import random

def randomBuildingIds(number_to_select):
    selected_buildings = random.sample(umich_buildings, number_to_select)
    building_ids = []
    for building in selected_buildings:
        building_ids.append(building["id"])
    return building_ids

bldgs = randomBuildingIds(5)
for b in bldgs:
    print(buildingLatLong(b))
```
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
('Central Campus Recreation Building', 42.278866, -83.732666)<br/>
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)<br/>
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)<br/>
None<br/>
('North Quadrangle', 42.280477, -83.740131)<br/>
('Michigan Stadium', 42.265071, -83.748662</div>

### <font color="blue">Problem 2</font>
"Vincenty's formulas are two related iterative methods used to calculate the distance between two points on the surface of a spheroid, developed by Thaddeus Vincenty (1975a)"

The file _Unit08_vincenty.py_, which was imported in the first cell, contains the function _latLngDistanceMeter_ that calculates the _vincenty_ distance" in meters between two points on the Earth using the latitude and longitude of each points. The function accepts two tuples each containing the latitude and longitude of a point and calculates the _vincenty_ distance between those points. Below is an example of how this function is called:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;latLngDistanceMeters((42.3584, -71.0912), (42.278, -83.7382))

Write a function named _buildingDistance_ that is passed two building IDs and determines the vincenty distance between both buildings. The function uses the function _buildingLatLong_, developed in the previous problem, to find the longitude and latidude of each building and calls _latLngDistanceMeters_ to determine and return the _vincenty_ distance.  If one or both building ids are invalid, i.e., buildingLatLong returns None, return _False_ as the distance.

In the main part of your code, iterate over the list _bldgs_ below and call _buildingDistance_ for each tuple in the list. Print the output below.

In [39]:
bldgs = [('ccrb','aep'),('taubl','nq'),('bid1','bid2'),('ccrb','bid1'),('bid2','bid2nq')]

def buildingDistance(id1, id2):
    # Get the coordinates for each building
    b1 = buildingLatLong(id1)
    b2 = buildingLatLong(id2)
    # Return False if either building id is invalid (not found)
    if b1 is None or b2 is None:
        return False
    # Pass the lat/lng of both buildings to latLngDistanceMeters and return the result
    return latLngDistanceMeters((b1[1], b1[2]), (b2[1], b2[2]))

# Iterate over the list of building pairs and print the vincenty distance for each
for pair in bldgs:
    dist = buildingDistance(pair[0], pair[1])
    print(f"The vincenty distance between building {pair[0]} and {pair[1]} is {dist}")

The vincenty distance between building ccrb and aep is 2414.804664314602
The vincenty distance between building taubl and nq is 575.5430991021018
The vincenty distance between building bid1 and bid2 is False
The vincenty distance between building ccrb and bid1 is False
The vincenty distance between building bid2 and bid2nq is False


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 2: Output Formatting and Comment Style

### The distance values are correct, but the printed output has many decimal places. For a distance in meters, showing 12 or more decimal places is usually more precision than the reader needs.

### Consider formatting the distance to two decimal places when it is a number. This makes the output easier to read while still communicating the result clearly.

```python
if dist is False:
    print(f"The vincenty distance between building {pair[0]} and {pair[1]} is {dist}")
else:
    print(f"The vincenty distance between building {pair[0]} and {pair[1]} is {dist:.2f} meters")
```

### Also notice the first-person comments again, such as `# I use...` and `# I return...`. Comments should explain the code directly instead of describing what the writer is doing.

```python
# Get the coordinates for each building
# Return False if either building id is invalid
```
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The vincenty distance between building ccrb and aep is 2414.804664314602<br />
The vincenty distance between building taubl and nq is 575.5430991014669<br />
The vincenty distance between building bid1 and bid2 is False<br />
The vincenty distance between building ccrb and bid1 is False<br />
The vincenty distance between building bid2 and bid2nq is False</div>

### <font color="blue">Problem 3:</font> 
Write code that iterates over _umich_buildings_ and outputs a _.csv_ file called _north_quad_distance.csv_. 

The csv file has two columns: 

1. The building name.
2. The vincenty distance of that building from North Quad(nq).

Since this is a csv file, the first row in the file is a header that identifies the two columns.  Column 1 of the first row has the value "Name" and column 2 has the value "Distance from NQ". There should be one subsequent row for each building (including North Quad, which should have a zero distance).  You should use the string .format() function to format each row in the csv file.

Check your work by opening the .csv file in a text editor or importing it into a spreadsheet program like Excel or Google Sheets.

You file should appear similar to that below:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name,Distance from NQ  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1000 Victors Way,4674.366005  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1032 Greene Building,1498.650608  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;523 South Division Building,639.5818755  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Administrative Services Building,1410.470849  

In [40]:
# Look up the coordinates of North Quad to use as the reference point
nq = buildingLatLong("nq")

# Create the output folder before writing the csv file
os.makedirs(output_dir, exist_ok=True)

# Open the output csv file for writing
f = open(north_quad_output_path, "w")

# Write the header row with column names
f.write("Name,Distance from NQ\n")

# Iterate over every building and calculate its distance from North Quad
for building in umich_buildings:
    dist = latLngDistanceMeters((nq[1], nq[2]), (building["lat"], building["lng"]))
    # Write each building name and distance as a formatted csv row
    f.write("{},{:.6f}\n".format(building["name"], dist))

f.close()
print("File written successfully.")
print("Output file:", north_quad_output_path)

File written successfully.
Output file: Data/Output/north_quad_distance.csv


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 3: Writing Output Files

### When writing a file, it is helpful to print the output path after the file is created. That confirmation tells you where the file was written, which is especially useful in notebooks because the current working directory may not always be obvious.

### In a project, generated files should usually go into a clear output folder instead of being written into the same flat folder as the notebook. For this assignment, a good structure is to place the CSV in `Data/Output`.

```python
output_dir = os.path.join(data_dir, "Output")
north_quad_output_path = os.path.join(output_dir, north_quad_output_filename)
print("Output file:", north_quad_output_path)
```

### Also notice the comment style: avoid first-person comments such as `# I write...`. A clearer comment describes the action directly, such as `# Write the header row with column names`.
</div>

### <font color="blue">Problem 4</font>
This problem uses the list _baby_names_ loaded from Unit08_us-common-baby-names.csv (see first cell). Each element in the baby_names list is a dictionary.  The keys in the dictionary are 'year', 'name','percent',and 'sex'.  A sample row appears below.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{'year': '1880', 'name': 'John', 'percent': '0.081541', 'sex': 'boy'}
             
The _percent_ key holds a percentage value, represented as a fraction, which represents the number of babies born that year who were given the name found in the value of the _name_ key.   

Write the function _popularInYear_ that accepts the  parameter _year_ and returns the most popular name for that year and the associated percent. The most popular name is the one with the largest percentage.  This problem is essentially finding the maximum percentage in the _baby_names_ list that matches the _year_ parameter.  

Write code the iterates over the _years_ list and prints the most popular name for each year as shown below.  Note, that you need to multiply the _percent_ value by 100 to print that value as a percentage.

In [41]:
years = ['1900','1925','1950','1975','2000','2004','2008']

def popularInYear(year):
    # Initialize best to None and update it when a higher percentage is found
    best = None
    for entry in baby_names:
        # Only consider entries that match the requested year
        if entry['year'] == year:
            if best is None or float(entry['percent']) > float(best['percent']):
                best = entry  # Update best when a higher percentage is found
    return best

# Iterate over each year and print the most popular name and its percentage
for year in years:
    result = popularInYear(year)
    print(f"Most popular name in {year} is {result['name']} with {float(result['percent'])*100:.2f} percent")

Most popular name in 1900 is John with 6.06 percent
Most popular name in 1925 is Mary with 5.59 percent
Most popular name in 1950 is James with 4.73 percent
Most popular name in 1975 is Michael with 4.22 percent
Most popular name in 2000 is Jacob with 1.65 percent
Most popular name in 2004 is Jacob with 1.32 percent
Most popular name in 2008 is Jacob with 1.04 percent


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 4: Percent Conversion and Comment Style

### Based on the instructions, it would be helpful to add a comment explaining how the percentage conversion works. In the data file, `percent` is stored as a fraction, so the code multiplies by `100` to display it as a human-readable percentage.

```python
percent_as_number = float(result["percent"])
percent_to_print = percent_as_number * 100
```

### For example, a value like `0.0606` means about `6.06 percent` after multiplying by `100`. The `:.2f` formatting then limits the printed value to two decimal places.

### Also continue watching for first-person comments. Instead of `# I initialize...`, use a direct description such as `# Initialize best to None and update it when a higher percentage is found`.
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
Most popular name in 1900 is John with 6.06 percent<br/>
Most popular name in 1925 is Mary with 5.59 percent<br/>
Most popular name in 1950 is James with 4.73 percent<br/>
Most popular name in 1975 is Michael with 4.22 percent<br/>
Most popular name in 2000 is Jacob with 1.65 percent<br/>
Most popular name in 2004 is Jacob with 1.32 percent<br/>
Most popular name in 2008 is Jacob with 1.04 percent</div>

### <font color="blue">Nested Data and Nested Iteration</font>
Many web services return information either in a json or xml format.  Below is sample json return by the Facebook API and is representative in structure of the json returned by most web services.  You will be working with nested data in future units.  This problem will serve as a warmup for those future problem sets.

First, just get familiar with the structure of the data. You may want to copy and paste it to a site like https://jsoneditoronline.org/ so you may inspect the data.

Run the cell below before proceeding to the problems.

In [43]:
fb_data = {
 "data": [
  {
    "id": "2253324325325123432madeup", 
    "from": {
      "id": "23243152523425madeup", 
      "name": "Jane Smith"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "This problem might use the accumulation pattern, like many problems do", 
    "type": "status", 
    "created_time": "2014-10-03T02:07:19+0000", 
    "updated_time": "2014-10-03T02:07:19+0000"
  }, 
 
  {
    "id": "2359739457974250975madeup", 
    "from": {
      "id": "4363684063madeup", 
      "name": "John Smythe"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "Here is a fun link about programming", 
    "type": "status", 
    "created_time": "2014-10-02T20:12:28+0000", 
    "updated_time": "2014-10-02T20:12:28+0000"
  }]
}

print("fb_data setup complete.")
print("Stored", len(fb_data["data"]), "posts in fb_data.")
print("First author:", fb_data["data"][0]["from"]["name"])

fb_data setup complete.
Stored 2 posts in fb_data.
First author: Jane Smith


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Nested Data: Confirming Setup and JSON Comments

### After creating a data structure like `fb_data`, it is helpful to print a short confirmation in the cell output. This confirms that the cell ran and that the expected data is now stored in the variable.

### In this case, the confirmation can show that the JSON-like dictionary was assigned to `fb_data`, how many posts are inside `fb_data["data"]`, and a small preview such as the first author name.

### Also note that true `.json` files do not support comments. Comments such as `# Explain this step` belong in Python code cells or Python files, not inside a normal JSON data file.
</div>

### <font color="blue">Problem 5</font>
Extract the contents of the first message into a variable called *first_message*.  Print *first_message*.

In [47]:
# Access the first item in the data list and extract its id and message values
first_message_id = fb_data["data"][0]["id"]
first_message = fb_data["data"][0]["message"]

print("Message id:", first_message_id)
print("Message:", first_message)

Message id: 2253324325325123432madeup
Message: This problem might use the accumulation pattern, like many problems do


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 5: Print IDs with Values

### When printing a value from nested data, include the unique identifier when one is available. The message text is useful, but the `id` tells you exactly which record the message came from.

### This is especially helpful when working with web service data because many records can have similar values. Printing both the identifier and the value makes the output easier to trace back to the original data.

```python
print("Message id:", first_message_id)
print("Message:", first_message)
```
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
This problem might use the accumulation pattern, like many problems do</div>

### <font color="blue">Problem 6<font>
Extract the name of the author of the second post, into a variable called *second_name*.  Print *second_name*.

In [51]:
# Navigate into the second post from dictionary to get the author id and name
second_author_id = fb_data["data"][1]["from"]["id"]
second_name = fb_data["data"][1]["from"]["name"]

print("Author id:", second_author_id)
print("Author name:", second_name)

Author id: 4363684063madeup
Author name: John Smythe


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 6: Store and Print Related Identifiers

### When storing data from a nested structure in a variable, printing a confirmation with the related `id` can make troubleshooting easier. If the value looks wrong, the id helps you trace the result back to the exact record.

### Examine the structure of each message: the `from` dictionary contains both a `name` and an `id`. Since those values describe the same author, it is helpful to print them together.

```python
print("Author id:", second_author_id)
print("Author name:", second_name)
```
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
John Smythe</div>

### <font color="blue">Problem 7</font>
Write code that generates a list of the names of all the authors of the messages in fb_data. Store it in a variable called _authors_.  Print the variable _authors_.

In [52]:
# Build a list of author names by iterating over every post in fb_data
authors = [post['from']['name'] for post in fb_data['data']]
print(authors)

['Jane Smith', 'John Smythe']


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 7: Store Names with Identifiers

### When working with a large list of names, it is very helpful to keep each name connected to its unique identifier. Names may repeat, but an `id` should point back to one specific record.

### The current list of names works for the assignment, but another useful output format would be a JSON-like dictionary with a `data` array. Each item could store both the user id and the user name.

```python
authors_with_ids = {
    "data": [
        {"id": "23243152523425madeup", "name": "Jane Smith"},
        {"id": "4363684063madeup", "name": "John Smythe"}
    ]
}
```

### This structure makes the data easier to store and reuse in a later step because each name still has the identifier needed to trace it back to the original message record.
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
['Jane Smith', 'John Smythe']</div>

### <font color="blue">Run the cell below before completing the problems that follow.</font>

In [63]:
zipCodeData = [
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Alpena",
            "longitude": "-83.4602",
            "post code": "49707",
            "latitude": "45.079"
         }
      ],
      "country": "United States",
      "place name": "Alpena",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Hubbard Lake",
            "longitude": "-83.6059",
            "post code": "49747",
            "latitude": "44.8947"
         }
      ],
      "country": "United States",
      "place name": "Hubbard Lake",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Suttons Bay",
            "longitude": "-85.6423",
            "post code": "49682",
            "latitude": "44.9656"
         }
      ],
      "country": "United States",
      "place name": "Suttons Bay",
      "state": "Michigan",
      "state abbreviation": "MI"
   }
]

zip_codes = []
states = []
for entry in zipCodeData:
    if entry["state"] not in states:
        states.append(entry["state"])
    for place in entry["places"]:
        zip_codes.append(place["post code"])

print("zipCodeData setup complete.")
print("Loaded", len(zip_codes), "zip codes.")
print("Loaded", len(states), "states.")
print("States:", states)

zipCodeData setup complete.
Loaded 3 zip codes.
Loaded 1 states.
States: ['Michigan']


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Zip Code Data: Load Confirmation

### When data is loaded or assigned, it is helpful to print a short summary of what is available. This gives you insight into the data before later cells depend on it.

### In a larger application, this kind of output is similar to logging. It helps with testing and troubleshooting because you can quickly confirm that the expected data loaded, how many records are available, and whether the contents match what you expected.

### For this cell, printing the number of zip code records and the number of states gives a quick check that `zipCodeData` was created successfully.
</div>

### <font color="blue">Problem 8</font>
Write code that iterates of the zipCodeData list and prints the nested _places_ list where the _place name_ (first-level place name) has a value of Hubbard Lake. 

In [65]:
# Iterate over zipCodeData and print the nested places list for Hubbard Lake
for entry in zipCodeData:
    if entry["place name"] == "Hubbard Lake":
        print(json.dumps(entry["places"], indent=2))

[
  {
    "place name": "Hubbard Lake",
    "longitude": "-83.6059",
    "post code": "49747",
    "latitude": "44.8947"
  }
]


<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 8: Readable Output Formatting

### The original output was technically correct, but it was printed as one long Python list. When the value is nested data, formatting the output can make it much easier to read.

### `json.dumps(..., indent=2)` prints the list in a JSON-style format with line breaks and indentation. This is useful for logging and notebook output because people can quickly see the structure of the data.

```python
print(json.dumps(entry["places"], indent=2))
```

### Clear output formatting matters in logs and messages. If the output is hard to scan, it becomes harder to test, troubleshoot, and confirm that the code found the correct record.
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
[{'place name': 'Hubbard Lake', 'longitude': '-83.6059', 'post code': '49747', 'latitude': '44.8947'}]</div>

### <font color="blue">Problem 9</font>
Write a function called _getZipData_ that accepts a _post code_ (zip code) as an argument and returns a tuple containing the associated _place name_, _longitude_, and _latitude_ for _zipCodeData_.  If the _post code_ passed to the function is not in the zipCodeData list, the returned tuple should have a value of None, 0, and 0 for the _place name_, _latitude_, and _longitude_ respectively.

Do the following in the function:
1. Initialize variables as necessary.
2. Iterate over _zipCodeData_: 
   1. Iterate over nexted _places_ list:
      1. If _post code_ in the current place is equal to the _post code_ passed:
         1. Store the _place name, _longitude_, and _latitude in the variables
3. Return the variables as a tuple

In [ ]:
def getZipData(post_code):
    # Initialize return values for the case where the zip code is not found
    place_name = None
    longitude = 0
    latitude = 0
    # Iterate over each entry in zipCodeData and then over its nested places list
    for entry in zipCodeData:
        for place in entry["places"]:
            # Check whether the current place post code matches the requested post code
            if place["post code"] == post_code:
                place_name = place["place name"]
                longitude = place["longitude"]
                latitude = place["latitude"]
    # Return a tuple of place name, longitude, and latitude
    return (place_name, longitude, latitude)

# Do not change the code below
for zipcode in ["49682","49707","11111"]:
     print(getZipData(zipcode))

<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 9: Comment Style Reminder

### This cell had several first-person comments, such as `# I initialize...`, `# I iterate...`, and `# I return...`. In code, comments should describe the purpose of the code rather than describe the writer doing the action.

### A clearer style is direct and task-focused:

```python
# Initialize return values for the case where the zip code is not found
# Check whether the current place post code matches the requested post code
# Return a tuple of place name, longitude, and latitude
```
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
('Suttons Bay', '-85.6423', '44.9656')<br />
('Alpena', '-83.4602', '45.079')<br />
(None, 0, 0)</div>

### <font color="blue">Problem 10</font>
Using the functions getZipData and latLngDistanceMeters write code that calculates the vincenty distance in kilometers between zip codes 49707 and 49747.  Print the output __exactly__ as shown below.  

The latLngDistanceMeters returns the distance in meters.  To convert to kilometers, divide the returned value by 1000.  

In [ ]:
# Look up the zip data for both zip codes using getZipData
data1 = getZipData("49707")  # Alpena
data2 = getZipData("49747")  # Hubbard Lake

# Convert meters to kilometers by dividing by 1000
dist = latLngDistanceMeters((float(data1[2]), float(data1[1])), (float(data2[2]), float(data2[1]))) / 1000

# Print the result formatted to 2 decimal places with the city names
print(f"The vincenty distance between {data1[0]} and {data2[0]} is {dist:.2f}km")

<div style="background-color:#fff4e5; color:#222; padding:12px; border-left:6px solid #f0a020; border-radius:6px;">

### 🛠️ Problem 10: Comment Style Reminder

### This cell repeats the first-person comment pattern with comments like `# I look up...`, `# I convert...`, and `# I print...`. The code is stronger when comments describe the action directly.

### For example, use `# Convert meters to kilometers by dividing by 1000` instead of `# I convert meters to kilometers by dividing by 1000`.
</div>

<div class="alert alert-warning">
    <font face="verdana" size="2" color="033971"><strong>Expected Output:</strong><br />
The vincenty distance between Alpena and Hubbard Lake is 23.48km</div>